import T from 'prop-types';
import Providers from './providers';
import { Header } from '@/components/page';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ height: '100%' }}>
      <body style={{ height: '100%' }}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: T.node
};
