const ACCEPTED_AUDIO_TYPES = ['.mp3', '.wav', '.flac', '.m4a'];
const MAX_AUDIO_CLIP_LENGTH = 5; // seconds
const MAX_AUDIO_SIZE = 1073741824; // 1GB
const MAX_AUDIO_LENGTH = 300; // seconds
const RESULTS_PAGE_SIZE = 2000;
const RESULTS_MAX = 6000;
const RESULTS_DISPLAY_PAGE_SIZE = 25;

export {
  ACCEPTED_AUDIO_TYPES,
  MAX_AUDIO_CLIP_LENGTH,
  MAX_AUDIO_SIZE,
  MAX_AUDIO_LENGTH,
  RESULTS_PAGE_SIZE,
  RESULTS_MAX,
  RESULTS_DISPLAY_PAGE_SIZE
};
