name: Deploy frontend to A2O GCP
on:
  workflow_dispatch: # allows for manual invocation
  workflow_run:
    workflows: [Test and lint]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.A2O_GOOGLE_CREDENTIALS }}
      with:
        credentials_json: '${{ secrets.A2O_GOOGLE_CREDENTIALS }}'

    - id: 'install-dependencies'
      name: 'Install dependencies'
      run: yarn install

    - name: 'Replace SEARCH_API value'
      run: find src/ -type f -name "*.js" -exec sed -i 's|bioacoustics.ds.io|search.acousticobservatory.org|g' {} +

    - id: 'build-production'
      name: 'Build Staging'
      run: yarn build

    - id: 'upload-folder-production'
      name: 'Upload Production'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'out'
        destination: 'bioacoustics-a2o-production-frontend'
        parent: false
