name: Deploy frontend to GCP
on:
  workflow_dispatch: # allows for manual invocation
  workflow_run:
    workflows: [Test and lint]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'install-dependencies'
      name: 'Install dependencies'
      run: yarn install

    - id: 'build-staging'
      name: 'Build Staging'
      run: yarn build

    - id: 'upload-folder-staging'
      name: 'Upload Staging'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'out'
        destination: 'bioacoustics-devseed-staging-frontend'
        parent: false
        predefinedAcl: publicRead
