name: Deploy frontend to GCP
on:
  workflow_dispatch: # allows for manual invocation
  push:
    branches:
      - main
      - gcp-deploy

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'build-staging'
      name: 'Build Staging'
      with:
        
    - id: 'upload-folder-staging'
      name: 'Upload Staging'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'out'
        destination: 'bioacoustics-devseed-staging-frontend'

    - id: 'uploaded-files-staging'
      uses: 'foo/bar@main'
      env:
        files: '${{ steps.upload-folder-staging.outputs.uploaded }}'